import { assignPlacementTeacher, bookPlacementSpeaking, cancelPlacementSpeakingBooking, cancelPlacementTestBooking, createPlacementTest, markPlacementFollowup, submitPlacementSpeakingScore, updatePlacementRawScores, updatePlacementSpeakingBooking, updatePlacementTestBooking, validatePlacementResult } from "@/app/actions";
import { Field, FormGrid, SelectField, TextAreaField } from "@/components/forms";
import { Empty, Flash, FormDetails, PageHeader, Panel, Status } from "@/components/ui";
import { requireRole } from "@/lib/auth";
import { formatDateTime } from "@/lib/format";
import { createClient } from "@/lib/supabase/server";

function joined(value: unknown): Record<string,any>|null { if (Array.isArray(value)) return value[0] || null; return value && typeof value === "object" ? value as Record<string,any> : null; }
function localDateTimeInput(value:string|null|undefined){
  if(!value) return "";
  const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(value));
  const v=Object.fromEntries(parts.map(x=>[x.type,x.value]));
  return `${v.year}-${v.month}-${v.day}T${v.hour}:${v.minute}`;
}
function slaLabel(row:any){ if(!row.completed_at) return "Chưa bắt đầu SLA trả điểm"; const due=new Date(row.completed_at).getTime()+12*3600*1000; const released=row.result_released_at?new Date(row.result_released_at).getTime():0; if(released) return released<=due?"Đã trả trong SLA 12h":"Đã trả nhưng quá SLA"; const left=due-Date.now(); return left>0?`Còn ${(left/3600000).toFixed(1)}h để trả điểm`:`Quá SLA ${Math.abs(left/3600000).toFixed(1)}h`; }

export default async function PlacementPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const profile=await requireRole(["admin","academic_manager","customer_service","teacher"]);
  const params=await searchParams; const supabase=await createClient();
  const {data: ownTeacher}=profile.role==="teacher"?await supabase.from("teachers").select("id,email,is_placement_assessor,full_name").eq("user_id",profile.id).maybeSingle():{data:null as any};
  const canCoordinate=["admin","academic_manager","customer_service"].includes(profile.role);
  const canValidate=["admin","academic_manager"].includes(profile.role);
  const [students,assessors,tests,bookings]=await Promise.all([
    canCoordinate?supabase.from("students").select("id,code,full_name,status").is("archived_at",null).order("full_name"):Promise.resolve({data:[] as any[]}),
    canCoordinate?supabase.from("teachers").select("id,code,full_name,email,is_placement_assessor").is("archived_at",null).order("full_name"):Promise.resolve({data:[] as any[]}),
    profile.role==="teacher"&&ownTeacher?supabase.from("placement_tests").select("*,students(id,code,full_name),teachers:assigned_teacher_id(id,code,full_name),placement_speaking_bookings(id,teacher_id,scheduled_start,duration_minutes,status,speaking_score,assessor_note,teachers(id,code,full_name))").eq("assigned_teacher_id",ownTeacher.id).order("scheduled_start"):supabase.from("placement_tests").select("*,students(id,code,full_name),teachers:assigned_teacher_id(id,code,full_name),placement_speaking_bookings(id,teacher_id,scheduled_start,duration_minutes,status,speaking_score,assessor_note,teachers(id,code,full_name))").order("created_at",{ascending:false}).limit(50),
    profile.role==="teacher"&&ownTeacher?.is_placement_assessor?supabase.from("placement_speaking_bookings").select("id,placement_test_id,scheduled_start,duration_minutes,status,speaking_score,assessor_note,placement_tests(id,status,students(code,full_name))").eq("teacher_id",ownTeacher.id).order("scheduled_start"):Promise.resolve({data:[] as any[]})
  ]);
  const founderEmails=["giaovien@gmail.com","baominh@gmail.com"];
  const assessorRows=(assessors.data||[]).filter((x:any)=>x.is_placement_assessor||founderEmails.includes(String(x.email||"").toLowerCase()));
  const ownIsAssessor=!!ownTeacher&&(ownTeacher.is_placement_assessor||founderEmails.includes(String(ownTeacher.email||"").toLowerCase()));
  if(profile.role==="teacher") return <><PageHeader eyebrow="Placement Test" title={`Placement workspace · ${ownTeacher?.full_name||profile.full_name}`} description="Full Placement được phân công riêng; Speaking 15 phút là một assignment khác."/>
    <div className="placement-urgent-note">
      <strong>Speaking 15 phút:</strong>
      ưu tiên book trước 12 giờ để dễ điều phối GV, nhưng booking gấp dưới 12 giờ vẫn được phép.
      CSKH cần chủ động xác nhận lại với GV/assessor.
    </div>
<Flash message={params.message} error={params.error}/>{tests.data?.length?<Panel title="Full Placement Test được phân công" description="Mở bài test online, theo dõi auto-score và nhập/confirm L-R-W nếu cần."><div className="placement-list">{tests.data.map((row:any)=>{const st=joined(row.students);return <article className="card placement-card" key={row.id}><div className="placement-card-head"><div><strong>{st?.code} · {st?.full_name}</strong><span>{formatDateTime(row.scheduled_start)} · {row.duration_minutes}p</span></div><Status value={row.status}/></div><div className="placement-owner-strip"><div><span>Code</span><strong>{row.external_token}</strong></div><div><span>Auto score</span><strong>{row.objective_auto_score!=null?`${row.objective_auto_score}/${row.objective_max_score||"?"}`:"Chưa sync"}</strong></div><a className="button button-yellow button-small" href={`/placement/test/${row.id}`} target="_blank">Mở Google Form</a></div><FormDetails title="Nhập / confirm điểm"><form action={updatePlacementRawScores} className="form-stack"><input type="hidden" name="placement_test_id" value={row.id}/><Field label="Listening" name="listening_score" type="number" min="0" max="9" step=".1" defaultValue={row.listening_score??""}/><Field label="Reading" name="reading_score" type="number" min="0" max="9" step=".1" defaultValue={row.reading_score??""}/><Field label="Writing" name="writing_score" type="number" min="0" max="9" step=".1" defaultValue={row.writing_score??""}/><TextAreaField label="Ghi chú" name="objective_note" defaultValue={row.objective_note||""}/><button className="button button-primary">Lưu điểm</button></form></FormDetails></article>})}</div></Panel>:null}{!ownIsAssessor?<Empty title="Tài khoản chưa bật Placement Assessor" description="Admin bật quyền assessor cho GV founder/tester."/>:<Panel title="Lịch Speaking của tôi" description="Booking Speaking được CSKH điều phối và tự đồng bộ sang Lịch dạy tuần của GV.">{bookings.data?.length?<div className="table-wrap"><table><thead><tr><th>HV</th><th>Lịch</th><th>Trạng thái</th><th>Chấm</th></tr></thead><tbody>{bookings.data.map((b:any)=>{const pt=joined(b.placement_tests); const st=joined(pt?.students); return <tr key={b.id}><td><strong>{st?.full_name}</strong><br/><span className="muted">{st?.code}</span></td><td>{formatDateTime(b.scheduled_start)} · 15p</td><td><Status value={b.status}/></td><td><form action={submitPlacementSpeakingScore} className="inline-edit-form"><input type="hidden" name="booking_id" value={b.id}/><Field label="Speaking score" name="speaking_score" type="number" step="0.1" required defaultValue={b.speaking_score??""}/><Field label="Nhận xét assessor" name="assessor_note" defaultValue={b.assessor_note||""}/><button className="button button-primary">Lưu Speaking</button></form></td></tr>})}</tbody></table></div>:<Empty title="Chưa có booking Speaking" description="CSKH book Speaking 15 phút; booking sẽ tự xuất hiện trong Lịch dạy của GV."/>}</Panel>}</>;

  return <><PageHeader eyebrow="Placement Operations" title="Placement Test" description="CSKH ghi nhận HV → book block test → book Speaking 15p → nhập điểm → Academic validate → CSKH trả điểm/follow-up ≤12h." actions={canCoordinate?<FormDetails title="+ Book Placement"><form action={createPlacementTest}><FormGrid><SelectField label="Học viên" name="student_id" required options={(students.data||[]).map((x:any)=>({value:x.id,label:`${x.code} · ${x.full_name}`}))}/><SelectField label="GV phụ trách Placement full test" name="assigned_teacher_id" options={(assessors.data||[]).map((x:any)=>({value:x.id,label:`${x.code} · ${x.full_name}`}))}/><Field label="Google Form URL" name="google_form_url" type="url" defaultValue="https://docs.google.com/forms/d/e/1FAIpQLSeomhHBjnWulq0oeOEVz55jI36LJJaQJrDDyzgHAacUFWHYPw/viewform?usp=send_form"/><SelectField label="Block test" name="duration_minutes" required options={[{value:"90",label:"90 phút · HV chưa biết IELTS / assessment ngắn"},{value:"180",label:"180 phút · HV đã biết IELTS / full test"}]}/><Field label="Bắt đầu" name="scheduled_start" type="datetime-local" required/><TextAreaField label="Ghi chú" name="note"/><button className="button button-primary">Book Placement</button></FormGrid></form></FormDetails>:null}/><Flash message={params.message} error={params.error}/>
  <Panel title="Placement pipeline" description="Điểm và SLA được giữ trên cùng hồ sơ trước khi xếp lớp.">{tests.data?.length?<div className="placement-list">{tests.data.map((row:any)=>{const student=joined(row.students); const speaking=joined(row.placement_speaking_bookings); return <article className="card placement-card" key={row.id}><div className="placement-card-head"><div><strong>{student?.code} · {student?.full_name}</strong><span>{row.duration_minutes} phút · {row.familiarity}</span></div><Status value={row.status}/></div><div className="placement-meta"><span>Test: {formatDateTime(row.scheduled_start)}</span><span className="sla-pill">{slaLabel(row)}</span></div>
    <div className="placement-owner-strip"><div><span>Placement owner</span><strong>{joined(row.teachers)?.full_name||"Chưa phân GV"}</strong></div><div><span>ZE Placement Code</span><strong>{row.external_token||"—"}</strong></div><div><span>Auto score</span><strong>{row.objective_auto_score!=null?`${row.objective_auto_score}/${row.objective_max_score||"?"}`:"Chưa sync"}</strong></div><a className="button button-yellow button-small" href={`/placement/test/${row.id}`} target="_blank">Mở bài test Online</a></div>
    <FormDetails title="Phân GV + Google Form" className="placement-owner-details"><form action={assignPlacementTeacher} className="form-stack"><input type="hidden" name="placement_test_id" value={row.id}/><SelectField label="GV phụ trách full Placement" name="teacher_id" defaultValue={row.assigned_teacher_id||""} options={(assessors.data||[]).map((x:any)=>({value:x.id,label:`${x.code} · ${x.full_name}`}))}/><Field label="Google Form URL" name="google_form_url" type="url" defaultValue={row.google_form_url||""}/><button className="button button-primary">Lưu phân công</button></form></FormDetails>
    <div className="placement-actions-grid">
      <FormDetails title="Sửa lịch Placement" className="placement-action-details placement-booking-action"><div className="placement-edit-stack"><form action={updatePlacementTestBooking} className="form-stack"><input type="hidden" name="placement_test_id" value={row.id}/><SelectField label="Block test" name="duration_minutes" required defaultValue={String(row.duration_minutes)} options={[{value:"90",label:"90 phút · New to IELTS / assessment ngắn"},{value:"180",label:"180 phút · Full test"}]}/><Field label="Đổi ngày / giờ" name="scheduled_start" type="datetime-local" required defaultValue={localDateTimeInput(row.scheduled_start)}/><TextAreaField label="Ghi chú" name="note" defaultValue={row.note||""}/><button className="button button-primary">Lưu lịch Placement mới</button></form><form action={cancelPlacementTestBooking} className="placement-cancel-form"><input type="hidden" name="placement_test_id" value={row.id}/><TextAreaField label="Lý do HV hủy / xóa khỏi lịch" name="reason" required/><button className="button button-danger">Hủy / xóa Placement khỏi lịch</button></form></div></FormDetails>
      <FormDetails title={speaking ? "Đổi Speaking / GV" : "Book Speaking 15p"} className="placement-action-details placement-speaking-action">{!speaking?<form action={bookPlacementSpeaking} className="form-stack"><input type="hidden" name="placement_test_id" value={row.id}/><SelectField label="Founder / Placement Assessor" name="teacher_id" required options={assessorRows.map((x:any)=>({value:x.id,label:`${x.code} · ${x.full_name}`}))}/><Field label="Speaking time" name="scheduled_start" type="datetime-local" required/><button className="button button-primary">Book Speaking 15p</button></form>:<div className="placement-edit-stack"><form action={updatePlacementSpeakingBooking} className="form-stack"><input type="hidden" name="booking_id" value={speaking.id}/><SelectField label="Đổi GV / Assessor" name="teacher_id" required defaultValue={speaking.teacher_id||""} options={assessorRows.map((x:any)=>({value:x.id,label:`${x.code} · ${x.full_name}`}))}/><Field label="Đổi ngày / giờ Speaking" name="scheduled_start" type="datetime-local" required defaultValue={localDateTimeInput(speaking.scheduled_start)}/><button className="button button-primary">Lưu lịch Speaking mới</button></form><form action={cancelPlacementSpeakingBooking} className="placement-cancel-form"><input type="hidden" name="booking_id" value={speaking.id}/><TextAreaField label="Lý do hủy Speaking" name="reason" required/><button className="button button-danger">Hủy / xóa Speaking khỏi lịch</button></form></div>}</FormDetails>
      <FormDetails title="Nhập điểm" className="placement-action-details placement-score-action"><form action={updatePlacementRawScores} className="form-stack"><input type="hidden" name="placement_test_id" value={row.id}/><Field label="Listening" name="listening_score" type="number" step="0.1" defaultValue={row.listening_score??""}/><Field label="Reading" name="reading_score" type="number" step="0.1" defaultValue={row.reading_score??""}/><Field label="Writing" name="writing_score" type="number" step="0.1" defaultValue={row.writing_score??""}/><Field label="Hoàn tất lúc" name="completed_at" type="datetime-local"/><TextAreaField label="Ghi chú objective" name="objective_note" defaultValue={row.objective_note||""}/><button className="button button-primary">Lưu điểm</button></form></FormDetails>
      {canValidate?<FormDetails title="Academic validate" className="placement-action-details placement-validate-action"><form action={validatePlacementResult} className="form-stack"><input type="hidden" name="placement_test_id" value={row.id}/><Field label="Entry level" name="entry_level" required defaultValue={row.entry_level||""}/><Field label="Overall score" name="overall_score" type="number" step="0.1" defaultValue={row.overall_score??""}/><TextAreaField label="Academic note" name="academic_note" defaultValue={row.academic_note||""}/><TextAreaField label="Recommendation / xếp lớp" name="recommendation" defaultValue={row.recommendation||""}/><button className="button button-primary">Validate kết quả</button></form></FormDetails>:null}
      {profile.role==="customer_service"||profile.role==="admin"?<FormDetails title="Trả điểm & follow-up" className="placement-action-details placement-followup-action"><form action={markPlacementFollowup} className="form-stack"><input type="hidden" name="placement_test_id" value={row.id}/><TextAreaField label="Nội dung follow-up" name="followup_note" required defaultValue={row.followup_note||""}/><button className="button button-yellow">Đã trả điểm / tư vấn</button></form></FormDetails>:null}
    </div><div className="placement-score-strip"><span>L {row.listening_score??"—"}</span><span>R {row.reading_score??"—"}</span><span>W {row.writing_score??"—"}</span><span>S {speaking?.speaking_score??"—"}</span><span>Level {row.entry_level||"—"}</span></div></article>})}</div>:<Empty title="Chưa có Placement booking" description="CSKH tạo booking từ hồ sơ HV và availability đã ghi nhận."/>}</Panel></>;
}
