import { bookPlacementSpeaking, createPlacementTest, markPlacementFollowup, submitPlacementSpeakingScore, updatePlacementRawScores, validatePlacementResult } from "@/app/actions";
import { Field, FormGrid, SelectField, TextAreaField } from "@/components/forms";
import { Empty, Flash, FormDetails, PageHeader, Panel, Status } from "@/components/ui";
import { requireRole } from "@/lib/auth";
import { formatDateTime } from "@/lib/format";
import { createClient } from "@/lib/supabase/server";

function joined(value: unknown): Record<string,any>|null { if (Array.isArray(value)) return value[0] || null; return value && typeof value === "object" ? value as Record<string,any> : null; }
function slaLabel(row:any){ if(!row.completed_at) return "Chưa bắt đầu SLA trả điểm"; const due=new Date(row.completed_at).getTime()+12*3600*1000; const released=row.result_released_at?new Date(row.result_released_at).getTime():0; if(released) return released<=due?"Đã trả trong SLA 12h":"Đã trả nhưng quá SLA"; const left=due-Date.now(); return left>0?`Còn ${(left/3600000).toFixed(1)}h để trả điểm`:`Quá SLA ${Math.abs(left/3600000).toFixed(1)}h`; }

export default async function PlacementPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const profile=await requireRole(["admin","academic_manager","customer_service","teacher"]);
  const params=await searchParams; const supabase=await createClient();
  const {data: ownTeacher}=profile.role==="teacher"?await supabase.from("teachers").select("id,is_placement_assessor,full_name").eq("user_id",profile.id).maybeSingle():{data:null as any};
  const canCoordinate=["admin","academic_manager","customer_service"].includes(profile.role);
  const canValidate=["admin","academic_manager"].includes(profile.role);
  const [students,assessors,tests,bookings]=await Promise.all([
    canCoordinate?supabase.from("students").select("id,code,full_name,status").is("archived_at",null).order("full_name"):Promise.resolve({data:[] as any[]}),
    canCoordinate?supabase.from("teachers").select("id,code,full_name,email,is_placement_assessor").eq("is_placement_assessor",true).is("archived_at",null).order("full_name"):Promise.resolve({data:[] as any[]}),
    profile.role==="teacher"?Promise.resolve({data:[] as any[]}):supabase.from("placement_tests").select("*,students(id,code,full_name),placement_speaking_bookings(id,teacher_id,scheduled_start,duration_minutes,status,speaking_score,assessor_note,teachers(id,code,full_name))").order("created_at",{ascending:false}).limit(50),
    profile.role==="teacher"&&ownTeacher?.is_placement_assessor?supabase.from("placement_speaking_bookings").select("id,placement_test_id,scheduled_start,duration_minutes,status,speaking_score,assessor_note,placement_tests(id,status,students(code,full_name))").eq("teacher_id",ownTeacher.id).order("scheduled_start"):Promise.resolve({data:[] as any[]})
  ]);
  if(profile.role==="teacher") return <><PageHeader eyebrow="Placement Test" title={`Speaking bookings · ${ownTeacher?.full_name||profile.full_name}`} description="Founder/test assessor nhận booking Speaking 15 phút tại đây."/>
    <div className="placement-urgent-note">
      <strong>Speaking 15 phút:</strong>
      ưu tiên book trước 12 giờ để dễ điều phối GV, nhưng booking gấp dưới 12 giờ vẫn được phép.
      CSKH cần chủ động xác nhận lại với GV/assessor.
    </div>
<Flash message={params.message} error={params.error}/>{!ownTeacher?.is_placement_assessor?<Empty title="Tài khoản chưa bật Placement Assessor" description="Admin bật quyền assessor cho GV founder/tester."/>:<Panel title="Lịch Speaking của tôi" description="Booking phải được CSKH tạo trước ít nhất 12 giờ.">{bookings.data?.length?<div className="table-wrap"><table><thead><tr><th>HV</th><th>Lịch</th><th>Trạng thái</th><th>Chấm</th></tr></thead><tbody>{bookings.data.map((b:any)=>{const pt=joined(b.placement_tests); const st=joined(pt?.students); return <tr key={b.id}><td><strong>{st?.full_name}</strong><br/><span className="muted">{st?.code}</span></td><td>{formatDateTime(b.scheduled_start)} · 15p</td><td><Status value={b.status}/></td><td><form action={submitPlacementSpeakingScore} className="inline-edit-form"><input type="hidden" name="booking_id" value={b.id}/><Field label="Speaking score" name="speaking_score" type="number" step="0.1" required defaultValue={b.speaking_score??""}/><Field label="Nhận xét assessor" name="assessor_note" defaultValue={b.assessor_note||""}/><button className="button button-primary">Lưu Speaking</button></form></td></tr>})}</tbody></table></div>:<Empty title="Chưa có booking Speaking" description="CSKH sẽ book GV assessor tối thiểu 12h trước giờ test."/>}</Panel>}</>;

  return <><PageHeader eyebrow="Placement Operations" title="Placement Test" description="CSKH ghi nhận HV → book block test → book Speaking 15p → nhập điểm → Academic validate → CSKH trả điểm/follow-up ≤12h." actions={canCoordinate?<FormDetails title="+ Book Placement"><form action={createPlacementTest}><FormGrid><SelectField label="Học viên" name="student_id" required options={(students.data||[]).map((x:any)=>({value:x.id,label:`${x.code} · ${x.full_name}`}))}/><SelectField label="Block test" name="duration_minutes" required options={[{value:"90",label:"90 phút · HV chưa biết IELTS / assessment ngắn"},{value:"180",label:"180 phút · HV đã biết IELTS / full test"}]}/><Field label="Bắt đầu" name="scheduled_start" type="datetime-local" required/><TextAreaField label="Ghi chú" name="note"/><button className="button button-primary">Book Placement</button></FormGrid></form></FormDetails>:null}/><Flash message={params.message} error={params.error}/>
  <Panel title="Placement pipeline" description="Điểm và SLA được giữ trên cùng hồ sơ trước khi xếp lớp.">{tests.data?.length?<div className="placement-list">{tests.data.map((row:any)=>{const student=joined(row.students); const speaking=joined(row.placement_speaking_bookings); return <article className="card placement-card" key={row.id}><div className="placement-card-head"><div><strong>{student?.code} · {student?.full_name}</strong><span>{row.duration_minutes} phút · {row.familiarity}</span></div><Status value={row.status}/></div><div className="placement-meta"><span>Test: {formatDateTime(row.scheduled_start)}</span><span className="sla-pill">{slaLabel(row)}</span></div>
    <div className="placement-actions-grid">
      <FormDetails title="Book Speaking 15p" className="placement-action-details placement-speaking-action"><form action={bookPlacementSpeaking} className="form-stack"><input type="hidden" name="placement_test_id" value={row.id}/><SelectField label="Founder / Placement Assessor" name="teacher_id" required defaultValue={speaking?.teacher_id||""} options={(assessors.data||[]).map((x:any)=>({value:x.id,label:`${x.code} · ${x.full_name}`}))}/><Field label="Speaking time" name="scheduled_start" type="datetime-local" required/><button className="button button-primary">Book ≥12h trước</button></form></FormDetails>
      <FormDetails title="Nhập điểm" className="placement-action-details placement-score-action"><form action={updatePlacementRawScores} className="form-stack"><input type="hidden" name="placement_test_id" value={row.id}/><Field label="Listening" name="listening_score" type="number" step="0.1" defaultValue={row.listening_score??""}/><Field label="Reading" name="reading_score" type="number" step="0.1" defaultValue={row.reading_score??""}/><Field label="Writing" name="writing_score" type="number" step="0.1" defaultValue={row.writing_score??""}/><Field label="Hoàn tất lúc" name="completed_at" type="datetime-local"/><TextAreaField label="Ghi chú objective" name="objective_note" defaultValue={row.objective_note||""}/><button className="button button-primary">Lưu điểm</button></form></FormDetails>
      {canValidate?<FormDetails title="Academic validate" className="placement-action-details placement-validate-action"><form action={validatePlacementResult} className="form-stack"><input type="hidden" name="placement_test_id" value={row.id}/><Field label="Entry level" name="entry_level" required defaultValue={row.entry_level||""}/><Field label="Overall score" name="overall_score" type="number" step="0.1" defaultValue={row.overall_score??""}/><TextAreaField label="Academic note" name="academic_note" defaultValue={row.academic_note||""}/><TextAreaField label="Recommendation / xếp lớp" name="recommendation" defaultValue={row.recommendation||""}/><button className="button button-primary">Validate kết quả</button></form></FormDetails>:null}
      {profile.role==="customer_service"||profile.role==="admin"?<FormDetails title="Trả điểm & follow-up" className="placement-action-details placement-followup-action"><form action={markPlacementFollowup} className="form-stack"><input type="hidden" name="placement_test_id" value={row.id}/><TextAreaField label="Nội dung follow-up" name="followup_note" required defaultValue={row.followup_note||""}/><button className="button button-yellow">Đã trả điểm / tư vấn</button></form></FormDetails>:null}
    </div><div className="placement-score-strip"><span>L {row.listening_score??"—"}</span><span>R {row.reading_score??"—"}</span><span>W {row.writing_score??"—"}</span><span>S {speaking?.speaking_score??"—"}</span><span>Level {row.entry_level||"—"}</span></div></article>})}</div>:<Empty title="Chưa có Placement booking" description="CSKH tạo booking từ hồ sơ HV và availability đã ghi nhận."/>}</Panel></>;
}
